/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualRouteImport } from './routes/visual'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as GameMultiplayerRouteImport } from './routes/game.multiplayer'
import { Route as GameLocalRouteImport } from './routes/game.local'
import { Route as GameAiRouteImport } from './routes/game.ai'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as GameMultiplayerRoomIdRouteImport } from './routes/game.multiplayer.$roomId'

const VisualRoute = VisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMultiplayerRoute = GameMultiplayerRouteImport.update({
  id: '/game/multiplayer',
  path: '/game/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLocalRoute = GameLocalRouteImport.update({
  id: '/game/local',
  path: '/game/local',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAiRoute = GameAiRouteImport.update({
  id: '/game/ai',
  path: '/game/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMultiplayerRoomIdRoute = GameMultiplayerRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => GameMultiplayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/pro': typeof ProRoute
  '/visual': typeof VisualRoute
  '/game/$id': typeof GameIdRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/multiplayer': typeof GameMultiplayerRouteWithChildren
  '/match/$id': typeof MatchIdRoute
  '/game/multiplayer/$roomId': typeof GameMultiplayerRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/pro': typeof ProRoute
  '/visual': typeof VisualRoute
  '/game/$id': typeof GameIdRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/multiplayer': typeof GameMultiplayerRouteWithChildren
  '/match/$id': typeof MatchIdRoute
  '/game/multiplayer/$roomId': typeof GameMultiplayerRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/pro': typeof ProRoute
  '/visual': typeof VisualRoute
  '/game/$id': typeof GameIdRoute
  '/game/ai': typeof GameAiRoute
  '/game/local': typeof GameLocalRoute
  '/game/multiplayer': typeof GameMultiplayerRouteWithChildren
  '/match/$id': typeof MatchIdRoute
  '/game/multiplayer/$roomId': typeof GameMultiplayerRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/matches'
    | '/pro'
    | '/visual'
    | '/game/$id'
    | '/game/ai'
    | '/game/local'
    | '/game/multiplayer'
    | '/match/$id'
    | '/game/multiplayer/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/matches'
    | '/pro'
    | '/visual'
    | '/game/$id'
    | '/game/ai'
    | '/game/local'
    | '/game/multiplayer'
    | '/match/$id'
    | '/game/multiplayer/$roomId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/matches'
    | '/pro'
    | '/visual'
    | '/game/$id'
    | '/game/ai'
    | '/game/local'
    | '/game/multiplayer'
    | '/match/$id'
    | '/game/multiplayer/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesRoute: typeof MatchesRoute
  ProRoute: typeof ProRoute
  VisualRoute: typeof VisualRoute
  GameIdRoute: typeof GameIdRoute
  GameAiRoute: typeof GameAiRoute
  GameLocalRoute: typeof GameLocalRoute
  GameMultiplayerRoute: typeof GameMultiplayerRouteWithChildren
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual': {
      id: '/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/multiplayer': {
      id: '/game/multiplayer'
      path: '/game/multiplayer'
      fullPath: '/game/multiplayer'
      preLoaderRoute: typeof GameMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/local': {
      id: '/game/local'
      path: '/game/local'
      fullPath: '/game/local'
      preLoaderRoute: typeof GameLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/ai': {
      id: '/game/ai'
      path: '/game/ai'
      fullPath: '/game/ai'
      preLoaderRoute: typeof GameAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/multiplayer/$roomId': {
      id: '/game/multiplayer/$roomId'
      path: '/$roomId'
      fullPath: '/game/multiplayer/$roomId'
      preLoaderRoute: typeof GameMultiplayerRoomIdRouteImport
      parentRoute: typeof GameMultiplayerRoute
    }
  }
}

interface GameMultiplayerRouteChildren {
  GameMultiplayerRoomIdRoute: typeof GameMultiplayerRoomIdRoute
}

const GameMultiplayerRouteChildren: GameMultiplayerRouteChildren = {
  GameMultiplayerRoomIdRoute: GameMultiplayerRoomIdRoute,
}

const GameMultiplayerRouteWithChildren = GameMultiplayerRoute._addFileChildren(
  GameMultiplayerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesRoute: MatchesRoute,
  ProRoute: ProRoute,
  VisualRoute: VisualRoute,
  GameIdRoute: GameIdRoute,
  GameAiRoute: GameAiRoute,
  GameLocalRoute: GameLocalRoute,
  GameMultiplayerRoute: GameMultiplayerRouteWithChildren,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
